# Generated by Django 3.2 on 2022-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_alter_leaverequest_type_of_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="type_of_leave",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("SICK_LEAVE", "Sick leave")],
                db_index=True,
                default="NORMAL",
                max_length=255,
            ),
        ),
    ]
