# Generated by Django 3.2 on 2022-02-15 07:39

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leaverequest_type_of_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(validators=[leave.models.validate_date_in_future]),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(validators=[leave.models.validate_date_in_future]),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', django.db.models.functions.datetime.Now()), ('start_date__lte', django.db.models.expressions.F('end_date'))), name='correct_date'),
        ),
    ]
