# Generated by Django 3.2 on 2022-02-15 07:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20220215_0739'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaverequest',
            name='correct_date',
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(check=models.Q(start_date__lte=django.db.models.expressions.F('end_date')), name='correct_date'),
        ),
    ]
